groups:
- name: leftovers
  jobs:
  - releasable
  - build-release
  - bump-brew-tap

resources:
- name: leftovers
  type: git
  source:
    branch: master
    uri: https://github.com/genevieve/leftovers.git

- name: release
  type: github-release
  source:
    owner: genevieve
    repository: leftovers
    access_token: ((leftovers_access_token))

- name: homebrew-tap
  type: git
  source:
    branch: master
    uri: git@github.com:genevieve/homebrew-tap.git
    private_key: ((tap_private_key))

jobs:
- name: build-release
  plan:
  - in_parallel:
    - get: release
    - get: leftovers
  - task: build-release-with-minor-bump
    file: leftovers/ci/tasks/build-release/task.yml
  - put: release
    params:
      name: builds/name
      tag: builds/name
      commitish: builds/commitish
      globs:
      - builds/bin/leftovers-*

- name: bump-brew-tap
  plan:
  - in_parallel:
    - get: leftovers
      passed: [build-release]
    - get: homebrew-tap
    - get: release
      passed: [build-release]
      trigger: true
      params:
        version: { tag: release/version }
        globs:
        - leftovers-*-darwin-amd64
        - leftovers-*-linux-amd64
  - task: bump-brew-tap
    file: leftovers/ci/tasks/bump-brew-tap/task.yml
  - put: homebrew-tap
    params:
      repository: updated-homebrew-tap/homebrew-tap
