name: test

on: [push, pull_request]

permissions:
  contents: read

jobs:
  mod:
    runs-on: ubuntu-latest
    name: Check modules
    steps:
    - name: Setup Go
      uses: actions/setup-go@v4
      with:
        go-version: 1.20.x

    - name: Checkout
      uses: actions/checkout@v3

    - name: Check mod file is updated
      run: go mod tidy && git diff --exit-code go.mod go.sum

  test:
    runs-on: ubuntu-latest
    name: Go ${{ matrix.version }}
    steps:
    - name: Setup Go
      uses: actions/setup-go@v4
      with:
        go-version: 1.20.x

    - name: Checkout
      uses: actions/checkout@v3

    - name: Install Ginkgo
      run: go install github.com/onsi/ginkgo/v2/ginkgo

    - name: Run vet
      run: go vet ./...

    - name: Run unit tests
      run: ginkgo -p -r -race -randomizeAllSpecs -randomizeSuites .
